import { LayoutSetup } from '@/presentation/components/shared/config/layout/LayoutSetup';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <LayoutSetup>
          {children}
        </LayoutSetup>
      </body>
    </html>
  );
}
