import { LayoutSetup } from '@/presentation/components/shared/config/layout/LayoutSetup';
import { LPHeader } from '@components/shared/header/LPHeader';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body>
        <LayoutSetup>
          <LPHeader />

          {children}
        </LayoutSetup>
      </body>
    </html>
  );
}
